# Generated by Django 5.2.4 on 2025-07-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateEnrollment',
            fields=[
            ],
            options={
                'verbose_name': 'Generated Certificate',
                'verbose_name_plural': 'Generated Certificates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lms_backend.enrollment',),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('EMPLOYEE', 'Employee')], max_length=10),
        ),
    ]
