# Generated by Django 5.2.4 on 2025-07-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0006_remove_otp_mobile_number_otp_email_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
