# Generated by Django 5.2.4 on 2025-07-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0009_certificate_delete_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_uuid',
            field=models.UUIDField(blank=True, editable=False, help_text='Unique UUID for this course certificate', null=True, unique=True),
        ),
    ]
