# Generated by Django 5.2.4 on 2025-07-30 07:05

import uuid
from django.db import migrations


def populate_course_uuids(apps, schema_editor):
    Course = apps.get_model('lms_backend', 'Course')
    for course in Course.objects.all():
        if not course.certificate_uuid:
            course.certificate_uuid = uuid.uuid4()
            course.save()


def reverse_populate_course_uuids(apps, schema_editor):
    Course = apps.get_model('lms_backend', 'Course')
    Course.objects.all().update(certificate_uuid=None)


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0010_course_certificate_uuid'),
    ]

    operations = [
        migrations.RunPython(populate_course_uuids, reverse_populate_course_uuids),
    ]
