# Generated by Django 5.2.4 on 2025-07-30 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0011_populate_course_uuids'),
    ]

    operations = [
    ]
