# Generated by Django 5.2.3 on 2025-07-30 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0012_populate_course_uuids'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('DELETE_COURSE', 'Delete Course'), ('DELETE_VIDEO', 'Delete Video'), ('DELETE_QUIZ', 'Delete Quiz'), ('DELETE_CATEGORY', 'Delete Category')], max_length=20)),
                ('object_id', models.IntegerField(help_text='ID of the object to be deleted')),
                ('object_title', models.CharField(help_text='Title/name of the object to be deleted', max_length=200)),
                ('message', models.TextField(blank=True, help_text='Optional message from the admin', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delete_requests', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Delete Request',
                'verbose_name_plural': 'Delete Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
