# Generated by Django 5.2.3 on 2025-07-30 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0013_request'),
    ]

    operations = [
    ]
