# Generated by Django 5.2.3 on 2025-07-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0016_alter_request_message_alter_request_request_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('DELETE_COURSE', 'Delete Course'), ('DELETE_VIDEO', 'Delete Video'), ('DELETE_QUIZ', 'Delete Quiz'), ('DELETE_CATEGORY', 'Delete Category'), ('DELETE_TEAM', 'Delete Team'), ('DELETE_USER', 'Delete User')], max_length=20),
        ),
    ]
