# Generated by Django 5.2.1 on 2025-08-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0019_add_undone_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_file', models.FileField(upload_to='certificate_templates/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name_x', models.IntegerField(default=420)),
                ('name_y', models.IntegerField(default=310)),
                ('course_x', models.IntegerField(default=420)),
                ('course_y', models.IntegerField(default=255)),
                ('uuid_x', models.IntegerField(default=420)),
                ('uuid_y', models.IntegerField(default=200)),
            ],
        ),
    ]
