# Generated by Django 5.2.3 on 2025-08-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0020_certificatetemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='course_font',
            field=models.CharField(default='Helvetica-Bold', help_text='Font for course name', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='course_font_size',
            field=models.IntegerField(default=14, help_text='Font size for course name'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_font',
            field=models.CharField(default='Helvetica-Bold', help_text='Font for student name', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='name_font_size',
            field=models.IntegerField(default=28, help_text='Font size for student name'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='uuid_font',
            field=models.CharField(default='Helvetica', help_text='Font for certificate UUID', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='uuid_font_size',
            field=models.IntegerField(default=10, help_text='Font size for certificate UUID'),
        ),
    ]
