# Generated by Django 5.2.4 on 2025-08-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0021_certificatetemplate_course_font_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_request_notification',
            field=models.BooleanField(default=False, help_text='Whether this notification is related to a request between staff and admin'),
        ),
    ]
