# Generated by Django 5.2.4 on 2025-08-25 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0028_add_user_to_courseassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image/thumbnail for the course', null=True, upload_to='course_covers/'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms_backend.course'),
        ),
    ]
