# Generated by Django 5.2.7 on 2026-03-27 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0029_course_cover_image_alter_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='custom_texts',
            field=models.JSONField(blank=True, default=list, help_text='Custom text elements added to certificate', null=True),
        ),
    ]
