# Generated by Django 5.2.7 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0030_certificatetemplate_custom_texts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_font',
            field=models.CharField(default='Times-Italic', help_text='Font for signature text', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_font_size',
            field=models.IntegerField(default=22, help_text='Font size for signature text'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_x',
            field=models.IntegerField(default=420),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='signature_y',
            field=models.IntegerField(default=520),
        ),
    ]
