# Generated by Django 5.2.7 on 2026-03-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0031_certificatetemplate_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='staff_signature_font',
            field=models.CharField(default='Times-Italic', help_text='Font for staff signature text', max_length=50),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='staff_signature_font_size',
            field=models.IntegerField(default=22, help_text='Font size for staff signature text'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='staff_signature_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='staff_signature_x',
            field=models.IntegerField(default=560),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='staff_signature_y',
            field=models.IntegerField(default=520),
        ),
    ]
