# Generated by Django 5.2.7 on 2026-04-22 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0032_certificatetemplate_staff_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_points',
            field=models.PositiveIntegerField(default=10, help_text='Credit points earned upon completing this course'),
        ),
        migrations.AlterField(
            model_name='request',
            name='request_type',
            field=models.CharField(choices=[('DELETE_COURSE', 'Delete Course'), ('DELETE_VIDEO', 'Delete Video'), ('DELETE_QUIZ', 'Delete Quiz'), ('DELETE_CATEGORY', 'Delete Category'), ('DELETE_TEAM', 'Delete Team'), ('DELETE_USER', 'Delete User'), ('STUDENT_REGISTRATION', 'Student Registration'), ('COURSE_ENROLLMENT', 'Course Enrollment')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserPointsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('points_to_next_level', models.IntegerField(default=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='points_summary', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('source_type', models.CharField(choices=[('COURSE_COMPLETION', 'Course Completion'), ('QUIZ_PERFORMANCE', 'Quiz Performance'), ('BONUS', 'Bonus Points'), ('ACHIEVEMENT', 'Achievement')], max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='lms_backend_user_id_d1fe15_idx')],
            },
        ),
    ]
