# Generated by Codex on 2026-04-27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_backend', '0033_course_credit_points_alter_request_request_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='course',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='certificate_templates',
                to='lms_backend.course',
            ),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='uploaded_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='uploaded_certificate_templates',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
